openapi: 3.0.1
info:
  title: API Compasso_Lisa
  description: API De Veiculos e Pessoas.
  version: 1.0.0
externalDocs:
  description: Documentação
  url: https://github.com/ItaloDavidb/API_COMPASSOLISA
servers:
- url: http://localhost:3000/api/v1
  description: Api Veiculos
paths:

  /car:
    get:
      summary: Retorna todos os Veiculos.
      parameters:
      - name: modelo
        in: query
        schema:
          type: string
        required: false
      - name: cor
        in: query
        schema:
          type: string
        required: false
      - name: ano
        in: query
        schema:
          type: string
        required: false
      - name: acessorios
        in: query
        schema:
          type: string
        required: false
      - name: quantidadePassageiros
        in: query
        schema:
          type: number
        required: false
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  employee:
                    type: array
                    items:
                      type: object
                      properties:
                        modelo:
                          type: string
                        cor:
                          type: string
                        ano: 
                          type: string
                        acessorios:
                          type: array
                          items: 
                            type: object
                            properties:
                              descricao:
                                type: string
                        quantidadePassageiros: 
                          type: number
        404:
          description: Veiculo não encontrado
          content:
            application/json: 
              example: "not found"
    post: 
      summary: Cria um novo Veiculo.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                modelo:
                  type: string
                cor:
                  type: string
                ano:
                  type: string
                acessorios:
                          type: array
                          items: 
                            type: object
                            properties:
                              descricao:
                                type: string
                quantidadePassageiros: 
                          type: number
      responses: 
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties: 
                  _id:
                    type: string
                  moddelo:
                    type: string
                  cor: 
                    type: string
                  ano:
                    type: string
                  acessorios:
                          type: array
                          items: 
                            type: object
                            properties:
                              descricao:
                                type: string
                  quantidadePassageiros: 
                    type: number


        400:
          description: Error
          content:
            application/json: 
              example: "não foi possivel cadastrar um novo Veiculo"
  /car/{car_id}:
    put:
      summary: Atualiza um Veiculo.
      parameters:
      - name: car_id
        in: path
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  _id:
                    type: string
                  moddelo:
                    type: string
                  cor: 
                    type: string
                  ano:
                    type: string
                  acessorios:
                          type: array
                          items: 
                            type: object
                            properties:
                              descricao:
                                type: string
                  quantidadePassageiros: 
                    type: number
      responses: 
        200:
          description: Atualizado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  moddelo:
                    type: string
                  cor: 
                    type: string
                  ano:
                    type: string
                  acessorios:
                          type: array
                          items: 
                            type: object
                            properties:
                              descricao:
                                type: string
                  quantidadePassageiros: 
                    type: number
        404:
          description: Funcionario não encontrado
          content:
            application/json: 
              example: "não foi possivel cadastrar o funcionário"
        400:
          description: Body Error
          content:
            application/json:
              example: "Body error"
    delete:
      summary: Atualiza um Veiculo.
      parameters:
      - name: car_id
        in: path
        schema:
          type: string
        required: true
      responses: 
        204:
          description: Excluido com sucesso
        404:
          description: Veiculo não encontrado
          content:
            application/json: 
              example: "não foi possivel cadastrar o Veiculo"
        400:
          description: Body Error
          content:
            application/json:
              example: "Body error"
  /people:
    post:
      summary: Cria uma nova Pessoa.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                cpf:
                  type: string
                data_nascimento:
                  type: string
                email:
                  type: string
                senha:
                  type: string
                habilitado:
                  type: string
      responses: 
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties: 
                  nome:
                    type: string
                  cpf:
                    type: string
                  data_nascimento:
                    type: string
                  email:
                    type: string
                  senha:
                    type: string
                  habilitado:
                    type: string
        400:
          description: Error
          content:
            application/json: 
              example: "não foi possivel cadastrar uma nova Pessoa"
    get:
      summary: Retorna todos as Pessoas.
      parameters:
      - name: nome
        in: query
        schema:
          type: string
        required: false
      - name: people_id
        in: query
        schema:
          type: string
        required: false
      - name: cpf
        in: query
        schema:
          type: string
        required: false
      - name: data_nascimento
        in: query
        schema:
          type: number
        required: false
      - name: email
        in: query
        schema:
          type: string
        required: false
      - name: senha
        in: query
        schema:
          type: string
        required: false
      - name: habilitado
        in: query
        schema:
          type: string
        required: false
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        nome:
                          type: string
                        people_id:
                          type: string
                        cpf: 
                          type: string
                        data_nascimento:
                          type: number
                        email:
                          type: string
                        senha:
                          type: string
                        habilitado:
                          type: string
        404:
          description: Pessoa não encontrado
          content:
            application/json: 
              example: "not found"
  /people/{people_id}:
    put:
      summary: Atualiza uma Pessoa.
      parameters:
      - name: people_id
        in: path
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                        nome:
                          type: string
                        people_id:
                          type: string
                        cpf: 
                          type: string
                        data_nascimento:
                          type: number
                        email:
                          type: string
                        senha:
                          type: string
                        habilitado:
                          type: string
      responses: 
        200:
          description: Atualizado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                        nome:
                          type: string
                        people_id:
                          type: string
                        cpf: 
                          type: string
                        data_nascimento:
                          type: number
                        email:
                          type: string
                        senha:
                          type: string
                        habilitado:
                          type: string
        404:
          description: Pessoa não encontrada
          content:
            application/json: 
              example: "não foi possivel cadastrar o funcionário"
        400:
          description: Body Error
          content:
            application/json:
              example: "Body error"
    delete:
      summary: Atualiza um Veiculo.
      parameters:
      - name: people_id
        in: path
        schema:
          type: string
        required: true
      responses: 
        204:
          description: Excluido com sucesso
        404:
          description: Pessoa não encontrada
          content:
            application/json: 
              example: "não foi possivel cadastrar o Veiculo"
        400:
          description: Body Error
          content:
            application/json:
              example: "Body error"
  /people/authenticate:
            post:
              summary: Autentica uma Pessoa
              requestBody:
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          email:
                            type: string
                          senha:
                            type: string
              responses: 
                  201:
                    description: Sucesso
                    content:
                      application/json:
                        schema:
                          type: object
                          properties: 
                            _id:
                              type: string
                            nome:
                              type: string
                            cpf: 
                              type: string
                            email:
                              type: string
                            habilitado:
                              type: string
                            token: 
                              type: string